API_TITLE: PROBATTER HAWKS SERVER API
API_VERSION: v1

# openapi.json version and URL prefix
OPENAPI_VERSION: 3.0.3
OPENAPI_URL_PREFIX: /

# Enable swagger UI
OPENAPI_SWAGGER_UI_PATH: /docs
OPENAPI_SWAGGER_UI_URL: https://cdn.jsdelivr.net/npm/swagger-ui-dist/

#VIDEO MANAGER CONFIGURATION
DEFAULT_VIDEO: /home/pi/workspace/hawks_batter/app_data/videos/v1.mpg
SETUP_FRAME: /home/pi/workspace/hawks_batter/app/data/setup.jpg

# Peripherals configuration
SENSOR_START_PIN: 21
SENSOR_STOP_PIN: 22
