API_TITLE: PROBATTER HAWKS SERVER API
API_VERSION: v1

# openapi.json version and URL prefix
OPENAPI_VERSION: 3.0.3
OPENAPI_URL_PREFIX: /

# Enable swagger UI
OPENAPI_SWAGGER_UI_PATH: /docs
OPENAPI_SWAGGER_UI_URL: https://cdn.jsdelivr.net/npm/swagger-ui-dist/

#VIDEO MANAGER CONFIGURATION
DEFAULT_VIDEO: /home/pi/workspace/hawks_probatter/app_data/videos/v1.mpg
SETUP_FRAME: /home/pi/workspace/hawks_probatter/app_data/setup.jpg
STARTUP_FRAME: /home/pi/workspace/hawks_probatter/app_data/startup.png

#MACHINE CONFIGURATION
DEFAULT_NUMBER_OF_PITCHES: 10

# Peripherals configuration
SENSOR_START_PIN: 23
SENSOR_STOP_PIN: 24
