version: 1
disable_existing_loggers: true

formatters:
  default:
    format: "%(asctime)s [%(threadName)s] [%(levelname)s] %(name)s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: default

  app:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: logs/app.log
    maxBytes: 52428800 # 50 Megabytes
    backupCount: 1

  video_manager:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: logs/manager/video.log
    maxBytes: 52428800 # 50 Megabytes
    backupCount: 1

  video_capture_interface:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: logs/interface/video_capture.log
    maxBytes: 52428800 # 50 Megabytes
    backupCount: 1
  
  api:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: logs/rest_api.log
    maxBytes: 52428800 # 50 Megabytes
    backupCount: 1


root:
  level: WARN
  handlers: [console]

loggers:
  server.app:
    level: INFO
    handlers: [app]
    propagate: no

  server.managers.video_manager:
    level: INFO
    handlers: [app]
    propagate: no
  
  server.managers.configuration_manager:
    level: INFO
    handlers: [app]
    propagate: no
  
  server.managers.sensors_manager:
    level: INFO
    handlers: [app]
    propagate: no
  
  server.managers.machine_manager:
    level: INFO
    handlers: [app]
    propagate: no

  server.interfaces.video_capture_interface:
    level: INFO
    handlers: [video_manager]
    propagate: no
  
  server.interfaces.keyboard_input_interface:
    level: INFO
    handlers: [app]
    propagate: no
  
  server.rest_api.configuration_controler:
    level: INFO
    handlers: [api]
    propagate: no
  
  server.rest_api.machine_controler:
    level: INFO
    handlers: [api]
    propagate: no